Hrms.Api/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace Hrms.Api.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

Hrms.Api/Models/EmployeeParameters.cs
using System;
using System.ComponentModel.DataAnnotations;
using Hrms.Domain.Enumerations;

namespace Hrms.Api.Models
{
    public class EmployeeParameters
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Date of Birth")]
        public DateTime DateOfBirth { get; set; }

        public Gender Gender { get; set; }
    }
}

Hrms.Api/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Hrms.Api.Areas.HelpPage.Models;

namespace Hrms.Api.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

Hrms.Api/Controllers/API/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper.QueryableExtensions;
using Hrms.Api.Controllers.API.Extensions;
using Hrms.Api.Infrastructure.Mappings;
using Hrms.Api.Models;
using Hrms.Domain.Dtos;
using Hrms.Domain.Employee.Add;
using Hrms.Domain.Employee.Add.Request;
using Hrms.Domain.Employee.Add.Response;
using Hrms.Domain.Entities;
using Hrms.Domain.Shared.ActionContext;
using Hrms.Persistence.Context;
using Hrms.Persistence.UnitOfWork;

namespace Hrms.Api.Controllers.API
{
    public class EmployeesController : ApiController
    {
        private readonly HrmsContext _context;
        private readonly IEmployeeAdder _employeeAdder;

        public EmployeesController(HrmsContext context, IEmployeeAdder employeeAdder)
        {
            _context = context;
            _employeeAdder = employeeAdder;
        }

        // GET api/employees
        public IList<EmployeeParameters> Get()
        {
            var uow = new UnitOfWork(_context);

            return uow.EmployeeRepository.GetAll()
                .ProjectTo<EmployeeParameters>(AutoMappings.Config)
                .ToList();
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/employees
        public HttpResponseMessage Post(EmployeeParameters employeeParameters)
        {
            var actionContext = ActionContext<EmployeeAddRequest, EmployeeAddResponse>.GetInstance(employeeParameters.ToEmployeeAddRequest(), new EmployeeAddResponse());
            _employeeAdder.ValidateRequest(actionContext);
            if (actionContext.ValidationResult.Get().Any())
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest, actionContext.ValidationResult.Get());
            }

            using (var uow = new UnitOfWork(_context))
            {
                var emp = AutoMappings.Mapper.Map<EmployeeParameters, Employee>(employeeParameters);

                uow.EmployeeRepository.Add(emp);
                uow.CommitUnitOfWork();
            }

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Hrms.Api/Controllers/UI/EmployeesController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Web.Mvc;
using Hrms.Domain.Enumerations;

namespace Hrms.Api.Controllers.UI
{
    public class EmployeesController : Controller
    { 
        //
        // GET: /Employees/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Employees/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Employees/Create

        public ActionResult Create()
        {
            IList<SelectListItem> genderList = new List<SelectListItem>
            {
                new SelectListItem()
                {
                    Text = Gender.Male.ToString(),
                    Value = ((int) Gender.Male).ToString(CultureInfo.InvariantCulture),
                    Selected = true
                },
                new SelectListItem()
                {
                    Text = Gender.Female.ToString(),
                    Value = ((int) Gender.Female).ToString(CultureInfo.InvariantCulture)
                },
                new SelectListItem()
                {
                    Text = Gender.Unknown.ToString(),
                    Value = ((int) Gender.Unknown).ToString(CultureInfo.InvariantCulture)
                }
            };

            ViewBag.GenderOptions = genderList;

            return View();
        }

        //
        // POST: /Employees/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // Ajax call to create new employee is fired using JQuery
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Employees/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Employees/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Employees/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Employees/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Hrms.Api/Controllers/UI/HomeController.cs
using System.Web.Mvc;

namespace Hrms.Api.Controllers.UI
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hrms.Api/Views/Employees/Create.cshtml
@model Hrms.Api.Models.EmployeeParameters

@{
    ViewBag.Title = "Create";
}

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#createEmployee").click(function () {

                $.ajax({
                    url: BASE_HREF + '/api/Employees',
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({
                        FirstName: $('#FirstName').val(),
                        LastName: $('#LastName').val(),
                        DateOfBirth: $('#DateOfBirth').val(),
                        Gender: $('#GenderOptions').val()
                    }),
                    success: function (data, status, xhr) {},
                    error: function (xhr, status, error) {
                        console.log(error);
                    }
                });
            });

            $('#DateOfBirth').datepicker({
                    changeMonth: true,
                    changeYear: true
                }
            );
        });       
    </script>
}

@section main
{
    <h5>Create New Employee</h5> 
    <br/>

    @using (Html.BeginForm())
    {
        @Html.HiddenFor(e => e.Id)

        <table>
            <tr>
                <td>
                    @Html.DisplayNameFor(e => e.FirstName)
                </td>
                <td>
                    @Html.TextBoxFor(e => e.FirstName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(e => e.LastName)
                </td>
                <td>
                    @Html.TextBoxFor(e => e.LastName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(e => e.DateOfBirth)
                </td>
                <td>
                    @Html.EditorFor(e => e.DateOfBirth)
                    @Html.ValidationMessageFor(e => e.DateOfBirth)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(e => e.Gender)
                </td>
                <td>
                    @Html.DropDownList("GenderOptions")
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button id="createEmployee" type="submit">Save New Employee</button>
                </td>
            </tr>
        </table>

    }
}

Hrms.Api/Views/Employees/Index.cshtml
@section scripts
{
    <script type="text/javascript" src="~/Scripts/Hrms/Employees.js"></script>
}

@section main
{
    <h5>Employee Details</h5>

    <br />

    <table id="employeesTable" class="display" width="100%"></table>
}

Hrms.Api/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Landing Page";
}

@section main
{  
    <h2>Welcome to HRMS Portal</h2>
    
    <img src="~/Images/landing.jpg" width="800" height="600"
         alt="Human Resource Management System"/>
}

Hrms.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <base href="http://localhost/HrmsService/"/>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/extensions")
    @Styles.Render("~/Content/themes/base/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/extensions")

    <script type="text/javascript">
        BASE_HREF = "http://localhost/HrmsService/";
    </script>
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">Human Resource Management System</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    
    @RenderSection("scripts", required: false)
    

    <div id="body">
        <section class="featured">
            <div class="content-wrapper">
                @Html.ActionLink("List Employees", "Index", "Employees")
                @Html.ActionLink("Create Employee", "Create", "Employees")
            </div>
        </section>
        
        <section class="content-wrapper main-content clear-fix">
            @RenderSection("main", required: true)
        </section>
    </div>
</body>
</html>